steps:
  # Unity WebGL 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/project'
      - 'game-ci/unity3d:2022.3.51f1-webgl'
      - unity-editor
      - -batchmode
      - -nographics
      - -quit
      - -projectPath
      - /project
      - -executeMethod
      - Builder.BuildWebGL
      - -logFile
      - /project/build.log

  # Storage에 업로드
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'builds/WebGL/*'
      - 'gs://${PROJECT_ID}-unity-builds/'

  # Cloud Run 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'unity-webgl'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# 로깅 옵션 설정
options:
  logging: CLOUD_LOGGING_ONLY
  
# 타임아웃 설정
timeout: '3600s'
